name: hisnelmoslem
description: A new Flutter project.

publish_to: 'none' 

version: 1.6.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.2.0
  rxdart: ^0.27.3
  material_design_icons_flutter: ^5.0.6595
  clipboard: ^0.1.3
  shared_preferences: ^2.0.12
  font_awesome_flutter: ^9.2.0
  sleek_circular_slider: ^2.0.1
  share: ^2.0.4
  sqflite: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  wakelock: ^0.6.1+1
  day_night_time_picker: ^1.0.5
  flutter_slidable: ^1.2.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  auto_size_text: ^3.0.0
  screenshot: ^1.2.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/quran/
    - assets/sounds/
    - assets/db/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf

