name: hisnelmoslem
description: Hisn Elmoslem.

publish_to: "none"

version: 2.8.0+24

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.9.3
  bloc: ^8.1.4
  bot_toast: ^4.1.3
  capture_widget:
    path: packages/capture_widget
  cupertino_icons: ^1.0.4
  day_night_time_picker: ^1.3.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^3.1.1
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  url_launcher: ^6.3.0
  vibration: ^2.0.0
  wakelock_plus: ^1.2.8
  window_manager: ^0.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/json/
    - assets/images/
    - assets/quran/
    - assets/sounds/
    - assets/db/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_v2-1.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey-Regular.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Regular.ttf
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf

flutter_intl:
  enabled: true
