name: hisnelmoslem
description: Hisn Elmoslem.

publish_to: "none"

version: 2.9.01+26

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  audioplayers: ^6.4.0
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.10.1
  bloc: ^9.0.0
  bot_toast: ^4.1.3
  capture_widget:
    path: packages/capture_widget
  cupertino_icons: ^1.0.8
  day_night_time_picker: ^1.3.1
  easy_debounce: ^2.0.3
  enum_to_string: ^2.2.1
  equatable: ^2.0.7
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_email_sender: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_slidable: ^4.0.0
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  get_storage: ^2.1.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  wakelock_plus: ^1.3.2
  window_manager: ^0.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

dependency_overrides:
  intl: ^0.19.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/json/
    - assets/images/
    - assets/quran/
    - assets/sounds/
    - assets/db/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_v2-1.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey-Regular.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Regular.ttf
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
