name: hisnelmoslem
description: Azkar and Tally.

publish_to: 'none' 

version: 1.1.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share: ^0.6.4+3

  
  
  cupertino_icons: ^0.1.3
  clipboard_manager: ^0.0.4
  material_design_icons_flutter: ^3.4.4595
  url_launcher: ^5.7.2
  shared_preferences: ^0.5.8
  flutter_local_notifications: ^1.4.4+2
  font_awesome_flutter: ^8.2.0
  open_appstore: ^1.0.2
  sleek_circular_slider: ^1.1.0
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




flutter:

  uses-material-design: true

  assets:
    - json/
    - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

